### ISSUE TITLE
Once logged, chrome loses the connection after refreshing

### ISSUE THREAD

**Issue by shaggybb** [sualko/jsxc#110]
Hi @sualko 
 
I'm using your example but only with some changes in xmpp properties
```
jsxc.init({
    ...
    loadSettings: function(username, password) {
        return {
            xmpp: {
                url: 'https://SERVER/http-bind',
                domain: 'SERVER',
                resource: 'jsxc',
                ...
            }
        };
    }
});
```
Once logged at chat, I can see user's list and do a chat but if I try to refresh chrome (F5 or Ctrl+R) it loses connection.   Here the console's log:

```
CONNFAIL: conflict jsxc.js:134 
XMPP connection failed: conflict jsxc.js:134 
DISCONNECTING: unknown stream-error jsxc.dep.js:4458 
POST https://SERVER/http-bind 404 (Invalid SID) jsxc.js:134 
DISCONNECTING: null jsxc.js:134 
DISCONNECTED: null jsxc.js:134 disconnected
``` 

Our xmpp server is TIGASE

Could you tell me what is wrong?

Iván

**Comment by sualko** [comment]
> Really, you don't need to store rid values due to the fact that you can use jsxc.xmpp.conn._proto.rid.

After a page refresh this value is null. How does strophe get this value?

> Additionally, I've detected that ridChange's listener is never used, hasn't it?

It is. https://github.com/sualko/jsxc/blob/master/jsxc.lib.js#L3245

**Comment by sualko** [comment]
Maybe 708648e4144ffe0be45ce2c4272e12d247b7ebcc fixes your issue.

**Comment by shaggybb** [comment]
Once the users has been attached, strophe.js sends a request each 30 seconds and it response with an increased rid (maybe our configuration of Tigase is wrong). To catch this rid and use it in next request I've used the connectionReady.jsxc event where we've included a new functionality in xmlOutput function.

There, we've triggered the ridChange event passing the last rid plus one to be used in the next request to our XMPP server.

Using two events provided by your app we are able to solve our problems and also without any change in your code. 

Do you think this is a proper way to use your app? 

Here the code we are used to solve it:
```javascript
$(document).one('connectionReady.jsxc', function(){

        //Set new rid after echo XMPP server response
        jsxc.xmpp.conn.xmlOutput = function(data) {
            if (jsxc.storage.getItem('debug') === true) {
                console.log('>', data);
            }

            if (jsxc.xmpp.conn && jsxc.xmpp.conn._proto && jsxc.xmpp.conn._proto.rid) {
                $(document).trigger('ridChange', [{rid: jsxc.xmpp.conn._proto.rid + 1}]);
            }

        };
    });
```

Thank you by your advices,
Iván

**Comment by sualko** [comment]
Normally it should work without any modifications, so I think it is a configuration issue. But if you could fix your issue, I will close both tickets.
