### ISSUE TITLE
Errors using same user at two places

### ISSUE THREAD

**Issue by shaggybb** [sualko/jsxc#111]
Hi @sualko 

I've connected the same user using empathy (ubuntu) and your example but with using different resources (user@domain/empathy and user@domain/jsxc) and I have found some problems in Firefox and Chrome (I have not tested in IE yet).

In chrome:
1. Clear localStorage in console (localStorage.clear())
2. Log in (Submit the login form) 
3. The users list is shown and there aren't errors in console
4. Logout
5. Log in (Submit the login form)
6. The users list doesn't appear.
7. Page refresh
8. Connection lost (see issue #110)

In firefox (with firebug):
1. Clear localStorage in console (localStorage.clear())
2. Log in (Submit the login form) 
3. The users list is shown but an error appears at console's log
![error_multiple_instance_of_user](https://cloud.githubusercontent.com/assets/1043952/5472514/c5db208a-8601-11e4-8368-ddfc8efef129.png)
4. Refreshing the page, there aren't errors.
5. Logout
6. Log in (Submit the login form) 
7. The user's list doesn't appear and there are the same error displayed at step 3.
8. Page refresh
9. The user's list appears and there aren't errors.

As appointment, I think that it should be the proper way but I am not able to see the connected user at empathy using your example.

Have you detected these bugs before?

Iván

**Comment by sualko** [comment]
I think you have an other problem, because that makes no sense in my eyes. But it is weird that it fix your issue. Do you try to log in from the same browser twice?

**Comment by sualko** [comment]
While testing an other issue, I stumbled across yours.

**Comment by shaggybb** [comment]
I started thinking it was something wrong in my config or in its way of usage but since now I am not feeling alone in the dark :P 

As you can seen, the bug seems easy to fix.

Thank you for your comment.

**Comment by shaggybb** [comment]
I've done some tests using the same logged user in multiple devices and it works perfectly.  Good fix!

Thanks @sualko
