### ISSUE TITLE
sjsxc does not start when logging in to webmail

### ISSUE THREAD

**Issue by aoster** [sualko/jsxc#112]
Hi all,

I have tried to install the lastest version (1.0.0) of sjsxc in my SOGo environment (v2.2.12) following the  
howto (https://github.com/sualko/jsxc/wiki/Install-sjsxc-(SOGo)). Unfortunately the XMPP client does not 
seem to work. As far as I can see the js code is loaded:

<script src="/SOGo.woa/WebServerResources/sjsxc/js/lib/jquery.ui.min.js?lm=1418982816" type="text/javascript"></script>
            <script src="/SOGo.woa/WebServerResources/sjsxc/js/jsxc/lib/jquery.colorbox-min.js?lm=1418982816" type="text/javascript"></script>
            <script src="/SOGo.woa/WebServerResources/sjsxc/js/jsxc/lib/jquery.slimscroll.js?lm=1418982816" type="text/javascript"></script>
            <script src="/SOGo.woa/WebServerResources/sjsxc/js/jsxc/lib/jquery.fullscreen.js?lm=1418982816" type="text/javascript"></script>
            <script src="/SOGo.woa/WebServerResources/sjsxc/js/jsxc/lib/jsxc.dep.min.js?lm=1418982816" type="text/javascript"></script>
            <script src="/SOGo.woa/WebServerResources/sjsxc/js/jsxc/jsxc.min.js?lm=1418982816" type="text/javascript"></script>
            <script src="/SOGo.woa/WebServerResources/sjsxc/js/sjsxc.config.js?lm=1418983252" type="text/javascript"></script>
            <script src="/SOGo.woa/WebServerResources/sjsxc/js/sjsxc.js?lm=1418982816" type="text/javascript"></script>

but the client is not visible.

I have two LDAP backends configured, one for user authentication and one as address source.

Could this be the problem ?

Thank you for your kind help.

best regards

Andreas

**Comment by aoster** [comment]
Hi Klaus, 

sorry for the late reply. I have been busy lately and did not find the
time to further investigate the 
issue. Luckily the problem fixed itself when I did install the latest
SOGo version, two days ago. 

Thank you for your kind support. 

best regards 

Andreas 

Am 2014-12-21 00:25, schrieb Klaus: 

> Sorry, jsxc config would be enough. Please send me some test credentials to klaus@jsxc.org, because everything looks good to me. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1] https://github.com/sualko/jsxc/issues/112#issuecomment-67753829

**Comment by sualko** [comment]
I'm glad that your chat works now.
