### ISSUE TITLE
Can't find some files in separate installation

### ISSUE THREAD

**Issue by itJunky** [sualko/jsxc#115]
i'm trying to install jsxc, but when i try an example, i can't see roaster and any others, except login page or page with message "You are logged in :-)."

in log i see 
2014/12/26 16:10:51 [error] 9747#0: *2944 open() "/www/hum.itjunky.ws/jsxc/build/jsxc.dep.js" failed (2: No such file or directory), client: 185.47.53.66, server: hum.itjunky.ws, request: "GET /jsxc/build/jsxc.dep.js HTTP/1.1", host: "hum.itjunky.ws", referrer: "http://hum.itjunky.ws/jsxc/example/index.html"

Or
2014/12/26 16:09:19 [error] 9747#0: *2928 open() "/www/hum.itjunky.ws/jsxc/lib/otr/build/otr.js" failed (2: No such file or directory), client: 185.47.53.66, server: hum.itjunky.ws, request: "GET /jsxc/lib/otr/build/otr.js HTTP/1.1", host: "hum.itjunky.ws", referrer: "http://hum.itjunky.ws/jsxc/example/login.html"

2014/12/26 16:09:19 [error] 9747#0: *2929 open() "/www/hum.itjunky.ws/jsxc/lib/otr/build/dep/salsa20.js" failed (2: No such file or directory), client: 185.47.53.66, server: hum.itjunky.ws, request: "GET /jsxc/lib/otr/build/dep/salsa20.js HTTP/1.1", host: "hum.itjunky.ws", referrer: "http://hum.itjunky.ws/jsxc/example/login.html"

2014/12/26 16:09:19 [error] 9747#0: *2929 open() "/www/hum.itjunky.ws/jsxc/lib/strophe.jingle/strophe.jingle.js" failed (2: No such file or directory

Why this files doesn't contain in repo?

**Comment by sualko** [comment]
> GET /jsxc/build/jsxc.dep.js 

You are right, this should be <code>/jsxc/build/lib/jsxc.dep.js</code>.

> Wtf, why i don't see any words in Readme about separatly needed clone repo otr and repo strophie.jingle? NEED info about it in Readme!

Please see "Developer notes" in [README.md](https://github.com/sualko/jsxc/#developer-notes).

> Who need to create dir http-bind? And what files it contain?

<code>/http-bind/</code> refers to your bosh interface. Have a look to our [manual](https://github.com/sualko/jsxc/wiki/Install-jsxc) and [bosh](https://en.wikipedia.org/wiki/BOSH).

**Comment by itJunky** [comment]
Thanks for reply :+1:
