### ISSUE TITLE
Not receiving video chat requests (ocjsxc)

### ISSUE THREAD

**Issue by cmaltais-quatral** [sualko/jsxc#116]
When I send a request for videochat it open the chat windows and i can see my webcam but the recipients don't see any notification that they are being called. 

We tried with Chrome and Firefox with no difference.

I followed the installation instructions here: https://github.com/sualko/jsxc/wiki/Install-ojsxc-(owncloud)

We are still able to send chat messages.

**Comment by sualko** [comment]
Please post your turn server configuration. Did you tried it in the same subnet?

**Comment by cmaltais-quatral** [comment]
We tried in the same network and two different network (clients) the server is in a remote location so we can't be in the same subnet as the server.

Here is my config:
http://pastebin.com/i99wSpnc

If you want I can give you access to the test server I have setup.

**Comment by sualko** [comment]
Please send your credentials to klaus@jsxc.org.

**Comment by cmaltais-quatral** [comment]
Email sent :)

**Comment by sualko** [comment]
Missing ice/turn values.
