### ISSUE TITLE
can't get jsxc client to login

### ISSUE THREAD

**Issue by isaganiesteron** [sualko/jsxc#117]
I followed instructions at https://github.com/sualko/jsxc/wiki/Install-jsxc 

I've openfire as my xmpp server, I followed the folder structure,I've added the files, configured the .js. file, set up paths, etc.

When I try to login, it just gives me the "Logging in... please wait" alert.

in my console I see this from the debug messages from jsxc.js(134):
New connection
CONNECTING: null

I can confirm my xmpp server is running since I can connect to it with the Spark IM client.

Am I missing anything?

**Comment by sualko** [comment]
Is your bosh module running? How is your bosh url?

**Comment by isaganiesteron** [comment]
just checked it now, and it seems I was using the wrong port. Thanks..

Although now I have "Chat login failed   Authentication failed with the chat server. Maybe the password is wrong?"

I am guessing this has to do with openfire configurations.
