### ISSUE TITLE
Port CSS to SCSS

### ISSUE THREAD

**Issue by dimaursu** [sualko/jsxc#118]
Hi there, 
I did some work recently in porting the project's CSS files to SCSS. More details in this pull-request -> 
https://github.com/diaspora/jsxc/pull/66

Is this stuff interesting to you? 
Can you cherry-pick the changes, or should I rebase to one of your branches, and submit a pull request?

**Comment by sualko** [comment]
That looks very interesting. I will try to have a deeper look at it this week.

**Comment by sualko** [comment]
Your work looks great and I would be happy to see a pull request of your changes, because that should simplify many things. If you need help, I will assist.
