### ISSUE TITLE
v1.1.0 beta

### ISSUE THREAD

**Issue by sualko** [sualko/jsxc#124]
Hi guys,

I just build [v1.1.0-beta](https://github.com/sualko/jsxc/releases/tag/v1.1.0-beta). Thanks to everybody, who contributed and helped to improve jsxc. If you have time, please test and report issues.

If no showstopper bug occurs, we will release 1.1.0 around Sunday. Together with this release I will also move all repositories to the new [jsxc organisation](https://github.com/jsxc) and delete the css/ folder.

@Zauberstuhl @dimaursu @jhass

Best regards,
Klaus

**Comment by dimaursu** [comment]
Nice! Good idea with the css/ folder, it confused me a lot in a diff.

**Comment by Zauberstuhl** [comment]
awesome ! I will have a look at my PR asap. Good job

**Comment by sualko** [comment]
@shaggybb

**Comment by shaggybb** [comment]
Nice! By the moment, everything seems work properly. 

I love ajax login!

**Comment by shaggybb** [comment]
Hi @sualko,

I have found that jsxc.gui.init method is called twice and it duplicates the jsxc_windowList and jsxc_windowListSB divs on the body. The first call is into jsxc.init and second into jsxc.xmpp.connected.

To avoid duplication, I have done this pull request #126 to try to resolve it. May be, there is another way to do that but for the moment it avoids the problem.
